### PR TITLE
Show command modal when modifying file scan

### LINKED ISSUE #1762: Enable "Fast File Scan" fails silently without client configured
When "Enable Scan" is pressed, the UI responds as if it were successful.  The only hints that it wasn't, is that it remains unconfigured if you revist the page and the below console output.

Web Console:
```
"Fetch error" Status(
    Status {
        code: 400,
        text: "Bad Request",
        category: ClientError,
    },
    FetchObject {
        request: Request {
            url: "/api/stratagem_configuration/",
            headers: {
                "Content-Type": "application/json; charset=utf-8",
                "X-CSRFToken": "WkpoF3z8M13FNxdYK6St2sPNEqbBt7wxrSOM4vfRU4vzV3vrZUwjxGZQ2umVHulo",
            },
            method: Post,
            body: Some(
                JsValue("{"filesystem":1,"interval":432000000,"report_duration":null,"purge_duration":null}"),
            ),
            cache: None,
            credentials: None,
            integrity: None,
            mode: None,
            redirect: None,
            referrer: None,
            referrer_policy: None,
            timeout: None,
            controller: RequestController {
                abort_controller: AbortController {
                    obj: Object {
                        obj: JsValue(AbortController),
                    },
                },
                timeout_handle: RefCell {
                    value: None,
                },
            },
        },
        result: Ok(
            ResponseWithDataResult {
                raw: Response {
                    obj: Object {
                        obj: JsValue(Response),
                    },
                },
                status: Status {
                    code: 400,
                    text: "Bad Request",
                    category: ClientError,
                },
                data: Err(
                    SerdeError(
                        Error("missing field `command`", line: 1, column: 144),
                        "{\"code\": \"stratagem_client_profile_not_installed\", \"message\": \"A client must be added with the \'Stratagem Client\' profile to run this command.\"}",
                    ),
                ),
            },
        ),
    },
)
```

### PR DESCRIPTION
**Pull request by ip1981**
updating-stratagem

Closes #1762, #2090.

Signed-off-by: Igor Pashev <pashev.igor@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2095)

### CODE REVIEW

File: iml-gui/crate/src/components/stratagem/mod.rs [hunk 1]
```diff
@@ -283,8 +283,10 @@ pub(crate) fn update(msg: Msg, cache: &ArcCache, model: &mut Model, orders: &mut
                 }
             }
             Msg::CmdSent(fetch_object) => match fetch_object.response() {
-                Ok(_) => {
-                    orders.skip();
+                Ok(x) => {
+                    let x = command_modal::Input::Commands(vec![Arc::new(x.data.command)]);
```
Comment (ip1981) [inline iml-gui/crate/src/components/stratagem/mod.rs:287]: This could be unified with other command_model consumers by using `fetch_json_data`, but might need  significant refactoring.

File: chroma_api/job.py [hunk 2]
```diff
@@ -31,7 +31,7 @@ def dehydrate_locked_item_content_type_id(self, bundle):
         if hasattr(locked_item, "content_type"):
             return locked_item.content_type.id
         else:
-            return ContentType.objects.get_for_model(locked_item)
+            return ContentType.objects.get_for_model(locked_item).id
```
Comment (ip1981) [inline chroma_api/job.py:34]: #2090

Comment (jgrund) [reply chroma_api/job.py:34]: Interesting we haven't hit this before, this code has not been changed in 8 years :)

File: iml-gui/crate/src/components/stratagem/mod.rs (hunk 1 above)
Comment (jgrund) [reply iml-gui/crate/src/components/stratagem/mod.rs:287]: Not worth it yet. There is a large seed 0.7 refactor looming, which redoes the fetch layer.
