### PR TITLE
Address immediate GUI visual bugs

### LINKED ISSUE #1708: Address immediate GUI visual bugs
There are a couple of gui bugs that need immediate fixing:
1. [x] - The right panel does not display properly in reponsive mode. For now, we should remove the right panel unless we are in a large view.
2. [x] - The volume table cell is rendering as a single column of text when the window is scaled down. We should fix the volume cell and also remove both the primary and failover server columns unless the browser is open in a medium view or larger.

### PR DESCRIPTION
**Pull request by johnsonw**
Fixes #1708.

Description:
There are a couple of gui bugs that need immediate fixing:

 - The right panel does not display properly in reponsive mode. For now, we should remove the right panel unless we are in a large view.
 - The volume table cell is rendering as a single column of text when the window is scaled down. We should fix the volume cell and also remove both the primary and failover server columns unless the browser is open in a medium view or larger.

Signed-off-by: johnsonw <wjohnson@whamcloud.com>

---
This change is [Reviewable](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1709)

### CODE REVIEW

File: iml-gui/crate/src/page/filesystem.rs [hunk 1]
```diff
@@ -421,8 +421,8 @@ fn targets(
                 t::thead_view(vec![
                     t::th_left(plain!["Name"]).merge_attrs(class![C.w_32]),
                     t::th_left(plain!["Volume"]),
-                    t::th_left(plain!["Primary Server"]).merge_attrs(class![C.w_48]),
-                    t::th_left(plain!["Failover Server"]).merge_attrs(class![C.w_48]),
+                    t::th_left(plain!["Primary Server"]).merge_attrs(class![C.w_48, C.hidden, C.md__table_cell]),
+                    t::th_left(plain!["Failover Server"]).merge_attrs(class![C.w_48, C.hidden, C.md__table_cell]),
                     t::th_left(plain!["Started on"]).merge_attrs(class![C.w_48]),
```
Comment (ip1981) [inline iml-gui/crate/src/page/filesystem.rs]: I was thinking how we could put all these servers in one cell. E. g. show only "started on" and mark it somehow whether it's the primary or a failover. Maybe show all servers in a popup.

Comment (johnsonw) [reply iml-gui/crate/src/page/filesystem.rs]: Yeah it's a good thought. Once things slow down perhaps we could look through the mocks a bit and make changes where necessary.
