### PR TITLE
Remove swap-emitter.timer

### LINKED ISSUE #2232: Start(ed|ing) IML Swap Emitter...
Seeing tons of Started/Starting IML Swap Emitter messages in the GUI logs.

Maybe only start it once?  Maybe not tell me when it succeeds, only fails?

Maybe filter the GUI logs for Warning/Error messages by default?

### PR DESCRIPTION
**Pull request by jgrund**
Due to systemd/systemd#9328, there is no way to silence a systemd timer.

To workaround this limitation, create a new daemon that will list swap
devices one per minute, but without logging each tick to the journal.

In addition, update mount-emitter to use latest futures and tokio.

Fixes #2232

Signed-off-by: Joe Grund <jgrund@whamcloud.io>

---
This change is [Reviewable](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2335)

### CODE REVIEW

File: device-scanner/mount-emitter/src/lib.rs [hunk 1]
```diff
@@ -8,67 +8,94 @@
...
-        FsType(x.remove("FSTYPE").expect("missing FSTYPE")),
-        MountOpts(x.remove("OPTIONS").expect("missing OPTIONS")),
+        MountPoint(
+            x.remove("TARGET")
+                .ok_or_else(|| Error::Missing("TARGET"))?
+                .into(),
+        ),
+        DevicePath(
+            x.remove("SOURCE")
+                .ok_or_else(|| Error::Missing("SOURCE"))?
```
Comment (ip1981) [inline device-scanner/mount-emitter/src/lib.rs:47]: Doesn't need to be `_else`?

**Review by ip1981 — APPROVED** [review]

File: device-scanner/mount-emitter/src/lib.rs (hunk 1 above)
Comment (jgrund) [reply device-scanner/mount-emitter/src/lib.rs:47]: Wasn't sure if clippy would complain about the allocation
