### PR TITLE
Redundant load fix

### LINKED ISSUE #1878: Command Modal loads redundant items
image

*Now*: Here we have all the items completed, however during opening/closing items the command and the jobs tree gets loaded again.

*Expected*: If some items get completed and cached, there is no need to load them again, the code should be aware of this and show the cached items immediately without any network traffic.

### PR DESCRIPTION
**Pull request by nlinker**
out

Precedes to the PR https://github.com/whamcloud/integrated-manager-for-lustre/pull/1899
Fixes #1878

---
This change is [Reviewable](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/1882)

### CODE REVIEW

File: iml-gui/crate/src/components/command_modal.rs [hunk 1]
```diff
@@ -683,20 +711,23 @@ impl Model {
         self.select = Default::default();
     }
 
-    fn assign_commands(&mut self, cmds: Vec<Arc<Command>>) {
-        self.commands = convert_to_rich_hashmap(cmds, extract_children_from_cmd);
+    fn update_commands(&mut self, cmds: Vec<Arc<Command>>) {
+        let commands = convert_to_rich_hashmap(cmds, extract_children_from_cmd);
+        self.commands.extend(commands);
```
Comment (nlinker) [inline iml-gui/crate/src/components/command_modal.rs:716]: Key part 2

File: iml-gui/crate/src/components/command_modal.rs [hunk 2]
```diff
@@ -683,20 +711,23 @@ impl Model {
...
         let tuple = self.check_back_consistency();
         self.refresh_view(tuple);
     }
 
-    fn assign_jobs(&mut self, jobs: Vec<Arc<Job0>>) {
-        self.jobs = convert_to_rich_hashmap(jobs, extract_children_from_job);
+    fn update_jobs(&mut self, jobs: Vec<Arc<Job0>>) {
+        let jobs = convert_to_rich_hashmap(jobs, extract_children_from_job);
+        self.jobs.extend(jobs);
```
Comment (nlinker) [inline iml-gui/crate/src/components/command_modal.rs:723]: Key part 2

File: iml-gui/crate/src/components/command_modal.rs [hunk 3]
```diff
@@ -683,20 +711,23 @@ impl Model {
...
         let tuple = self.check_back_consistency();
         self.refresh_view(tuple);
     }
 
-    fn assign_steps(&mut self, steps: Vec<Arc<Step>>) {
-        self.steps = convert_to_rich_hashmap(steps, extract_children_from_step);
+    fn update_steps(&mut self, steps: Vec<Arc<Step>>) {
+        let steps = convert_to_rich_hashmap(steps, extract_children_from_step);
+        self.steps.extend(steps);
```
Comment (nlinker) [inline iml-gui/crate/src/components/command_modal.rs:730]: Key part 2

File: iml-gui/crate/src/components/command_modal.rs [hunk 4]
```diff
@@ -200,17 +199,23 @@ pub fn update(msg: Msg, model: &mut Model, orders: &mut impl Orders<Msg, GMsg>)
 
 fn schedule_fetch_tree(model: &mut Model, orders: &mut impl Orders<Msg, GMsg>) {
     let (cmd_ids, job_ids, _) = &model.select.split();
-    let load_cmd_ids = extract_sorted_keys(&model.commands);
+    // grab all the dependencies for the chosen items, except those that already loaded and completed
+    let load_cmd_ids = extract_sorted_keys(&model.commands)
+        .into_iter()
+        .filter(|c| to_load_cmd(model, *c))
```
Comment (nlinker) [inline iml-gui/crate/src/components/command_modal.rs:205]: Key part 1

File: iml-gui/crate/src/components/command_modal.rs [hunk 5]
```diff
@@ -200,17 +199,23 @@ pub fn update(msg: Msg, model: &mut Model, orders: &mut impl Orders<Msg, GMsg>)
...
+        .collect::<Vec<u32>>();
     let load_job_ids = cmd_ids
         .iter()
-        .filter(|id| model.commands.contains_key(id))
-        .flat_map(|id| model.commands[id].deps())
+        .filter(|c| model.commands.contains_key(c))
+        .flat_map(|c| model.commands[c].deps())
+        .filter(|j| to_load_job(model, **j))
```
Comment (nlinker) [inline iml-gui/crate/src/components/command_modal.rs:211]: Key part 1

File: iml-gui/crate/src/components/command_modal.rs [hunk 6]
```diff
@@ -200,17 +199,23 @@ pub fn update(msg: Msg, model: &mut Model, orders: &mut impl Orders<Msg, GMsg>)
...
         .copied()
         .collect::<Vec<u32>>();
     let load_step_ids = job_ids
         .iter()
-        .filter(|id| model.jobs.contains_key(id))
-        .flat_map(|id| model.jobs[id].deps())
+        .filter(|j| model.jobs.contains_key(j))
+        .flat_map(|j| model.jobs[j].deps())
+        .filter(|s| to_load_step(model, **s))
```
Comment (nlinker) [inline iml-gui/crate/src/components/command_modal.rs:218]: Key part 1

File: iml-gui/crate/src/components/command_modal.rs [hunk 7]
```diff
@@ -572,12 +577,36 @@ fn extract_uri_id<T: EndpointName>(input: &str) -> Option<u32> {
     })
 }
 
-fn is_finished(cmd: &RichCommand) -> bool {
-    cmd.complete
+fn to_load_cmd(model: &Model, cmd_id: u32) -> bool {
+    // load it if the command is not found or is not complete
```
Comment (ip1981) [inline iml-gui/crate/src/components/command_modal.rs:581]: load what? This comment is confusing :)

File: iml-gui/crate/src/components/command_modal.rs [hunk 8]
```diff
@@ -572,12 +577,36 @@ fn extract_uri_id<T: EndpointName>(input: &str) -> Option<u32> {
...
+}
+
+fn to_load_job(model: &Model, job_id: u32) -> bool {
+    if let Some(job) = model.jobs.get(&job_id) {
+        // job.state can be "tasked", "pending" or "complete"
+        // if a job is errored or cancelled, it is also complete
+        job.state != "complete"
+    } else {
+        true
+    }
```
Comment (ip1981) [inline iml-gui/crate/src/components/command_modal.rs:596]:
```suggestion
    model.jobs.get(&job_id).map(|j| j.state != "complete").unwrap_or(true)
```
Nit: shorter and linear ;-)

File: iml-gui/crate/src/components/command_modal.rs (hunk 7 above)
Comment (nlinker) [reply iml-gui/crate/src/components/command_modal.rs:581]: It = the command with the id `cmd_id`. If you want it to update, I can do this here: https://github.com/whamcloud/integrated-manager-for-lustre/pull/1899
(it sits on top of the current one)

File: iml-gui/crate/src/components/command_modal.rs [hunk 9]
```diff
@@ -572,12 +577,36 @@ fn extract_uri_id<T: EndpointName>(input: &str) -> Option<u32> {
...
+}
+
+fn to_load_step(model: &Model, step_id: u32) -> bool {
+    if let Some(step) = model.steps.get(&step_id) {
+        // step.state can be "success", "failed" or "incomplete"
+        step.state != "success" && step.state != "failed"
```
Comment (johnsonw) [inline iml-gui/crate/src/components/command_modal.rs:602]: This will work but if we are comparing state I really think we should be using an enum as opposed to a string.

File: iml-gui/crate/src/components/command_modal.rs (hunk 8 above)
Comment (nlinker) [reply iml-gui/crate/src/components/command_modal.rs:596]: It is already done in https://github.com/whamcloud/integrated-manager-for-lustre/pull/1899 as well :-)

Comment (ip1981) [reply iml-gui/crate/src/components/command_modal.rs:596]: Ok, I thought it was déjà vu :)

File: iml-gui/crate/src/components/command_modal.rs (hunk 7 above)
Comment (ip1981) [reply iml-gui/crate/src/components/command_modal.rs:581]: I would just not write any comments ;-)

File: iml-gui/crate/src/components/command_modal.rs (hunk 9 above)
Comment (nlinker) [reply iml-gui/crate/src/components/command_modal.rs:602]: Fair point, I'll create the issue, since making the model more type safe is outside the scope of the task the PR is solving.

Comment (jgrund) [reply iml-gui/crate/src/components/command_modal.rs:602]: This can be done (and is a good idea), but it will need to updated in the wire-types since this is referencing an API step.

Comment (johnsonw) [reply iml-gui/crate/src/components/command_modal.rs:602]: sounds good to me. I'll +1
